version: '3'

services:
  apisolid:
    image: bitnami/postgresql
    ports: 
      - 4321:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid